name: psw-sqli-02-login-bypass

services:
  web:
    build: .
    image: psw-sqli-02-login-bypass:latest
    container_name: psw-sqli-02-login-bypass
    hostname: psw-sqli-02-login-bypass
    ports:
      - "127.0.0.1:18002:8000"
    restart: "no"
    environment:
      - DJANGO_SETTINGS_MODULE=sqli_lab.settings
    labels:
      - "lab.suite=portswigger"
      - "lab.topic=sql-injection"
      - "lab.id=psw-sqli-02-login-bypass"
      - "lab.title=SQLi allowing login bypass"
    networks:
      - psw-sqli-02-login-bypass-net

networks:
  psw-sqli-02-login-bypass-net:
    name: psw-sqli-02-login-bypass-net
    driver: bridge
